[package]
name = "cdd"
version = "0.1.0"
authors = ["Rob Saunders <rob@wearebrandnew.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
